spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 12345678
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: 'ALL'
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
